spring:
  application:
    name: gateway
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    read:
      max-string-length: 50MB

server:
  port: ${PORT:8080}
  tomcat:
    max-http-post-size: 50MB
    max-swallow-size: 50MB

ai:
  service:
    url: ${AI_SERVICE_URL:https://kryptos-backend-289445394265.us-central1.run.app}
